import type * as monacoNs from 'monaco-editor/esm/vs/editor/editor.api'

export type ThemeName = 'dark' | 'light'

export const MONACO_THEME: Record<ThemeName, string> = {
  dark: 'jsonlens-dark',
  light: 'jsonlens-light',
}

/**
 * An original IDE-flavoured palette: near-neutral chrome, one blue accent, and
 * syntax hues that stay legible without shouting. Diff colours are deliberately
 * low-saturation washes — the gutter marker carries the signal, the background
 * only locates it.
 */
const dark: monacoNs.editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'ccd1d9', background: '191c21' },
    { token: 'string.key.json', foreground: '9dbbe8' },
    { token: 'string.value.json', foreground: 'a3c58a' },
    { token: 'string', foreground: 'a3c58a' },
    { token: 'number', foreground: 'd9a05b' },
    { token: 'keyword.json', foreground: 'c08fd6' },
    { token: 'keyword', foreground: 'c08fd6' },
    { token: 'delimiter', foreground: '707886' },
    { token: 'delimiter.bracket', foreground: '99a0ad' },
    { token: 'delimiter.array', foreground: '99a0ad' },
    { token: 'comment', foreground: '5f6875', fontStyle: 'italic' },
    { token: 'invalid', foreground: 'd3757c' },
  ],
  colors: {
    'editor.background': '#191c21',
    'editor.foreground': '#ccd1d9',
    'editorLineNumber.foreground': '#4d5563',
    'editorLineNumber.activeForeground': '#9aa2b0',
    'editor.lineHighlightBackground': '#1f232a',
    'editor.lineHighlightBorder': '#00000000',
    'editorCursor.foreground': '#4d9cf6',
    'editor.selectionBackground': '#2f4a6b',
    'editor.inactiveSelectionBackground': '#27374a',
    'editor.selectionHighlightBackground': '#2a3b52',
    'editor.wordHighlightBackground': '#2a3b52',
    'editor.findMatchBackground': '#4a5a2f',
    'editor.findMatchHighlightBackground': '#3a4728',
    'editorIndentGuide.background1': '#272b33',
    'editorIndentGuide.activeBackground1': '#3d4450',
    'editorBracketMatch.background': '#2f4a6b66',
    'editorBracketMatch.border': '#4d9cf6aa',
    'editorGutter.background': '#191c21',
    'editorWhitespace.foreground': '#2c3038',
    'editorError.foreground': '#d3757c',
    'editorWarning.foreground': '#cf9a4e',
    'editorOverviewRuler.border': '#00000000',
    'editorOverviewRuler.addedForeground': '#4f8f63cc',
    'editorOverviewRuler.deletedForeground': '#a85a62cc',
    'editorOverviewRuler.modifiedForeground': '#b8863acc',
    'editorOverviewRuler.errorForeground': '#d3757c',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#3a404b80',
    'scrollbarSlider.hoverBackground': '#4a5261b0',
    'scrollbarSlider.activeBackground': '#5a6371c0',
    'editorWidget.background': '#21252c',
    'editorWidget.border': '#333944',
    'editorWidget.foreground': '#ccd1d9',
    'editorHoverWidget.background': '#21252c',
    'editorHoverWidget.border': '#333944',
    'editorSuggestWidget.background': '#21252c',
    'editorSuggestWidget.border': '#333944',
    'editorSuggestWidget.selectedBackground': '#2c3440',
    'input.background': '#1b1f25',
    'input.border': '#333944',
    'input.foreground': '#ccd1d9',
    'inputOption.activeBorder': '#4d9cf6',
    'focusBorder': '#4d9cf6',
    'list.hoverBackground': '#242931',
    'list.activeSelectionBackground': '#2c3440',
    'list.focusBackground': '#2c3440',
    'diffEditor.insertedTextBackground': '#4f8f6326',
    'diffEditor.removedTextBackground': '#a85a6226',
    'diffEditor.insertedLineBackground': '#4f8f6318',
    'diffEditor.removedLineBackground': '#a85a6218',
    'diffEditorGutter.insertedLineBackground': '#4f8f6322',
    'diffEditorGutter.removedLineBackground': '#a85a6222',
    'diffEditorOverview.insertedForeground': '#4f8f63aa',
    'diffEditorOverview.removedForeground': '#a85a62aa',
    'diffEditor.diagonalFill': '#2b3038',
    'minimap.background': '#191c21',
  },
}

const light: monacoNs.editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '24282f', background: 'ffffff' },
    { token: 'string.key.json', foreground: '1f4f9e' },
    { token: 'string.value.json', foreground: '2f6b31' },
    { token: 'string', foreground: '2f6b31' },
    { token: 'number', foreground: '9a4a12' },
    { token: 'keyword.json', foreground: '6f2fa0' },
    { token: 'keyword', foreground: '6f2fa0' },
    { token: 'delimiter', foreground: '77808d' },
    { token: 'delimiter.bracket', foreground: '4b5361' },
    { token: 'delimiter.array', foreground: '4b5361' },
    { token: 'comment', foreground: '8a919c', fontStyle: 'italic' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#24282f',
    'editorLineNumber.foreground': '#adb4bf',
    'editorLineNumber.activeForeground': '#5c6472',
    'editor.lineHighlightBackground': '#f4f6f9',
    'editor.lineHighlightBorder': '#00000000',
    'editorCursor.foreground': '#1f6fd0',
    'editor.selectionBackground': '#cfe2fb',
    'editorIndentGuide.background1': '#eceef2',
    'editorIndentGuide.activeBackground1': '#d3d8e0',
    'editorBracketMatch.background': '#cfe2fb88',
    'editorBracketMatch.border': '#1f6fd0aa',
    'editorGutter.background': '#ffffff',
    'editorError.foreground': '#c1444d',
    'editorWidget.background': '#ffffff',
    'editorWidget.border': '#dfe3ea',
    'editorHoverWidget.background': '#ffffff',
    'editorHoverWidget.border': '#dfe3ea',
    'scrollbarSlider.background': '#c3c9d360',
    'scrollbarSlider.hoverBackground': '#adb4bf90',
    'scrollbarSlider.activeBackground': '#98a0ada0',
    'diffEditor.insertedTextBackground': '#3f8b5326',
    'diffEditor.removedTextBackground': '#c1444d22',
    'diffEditor.insertedLineBackground': '#3f8b5316',
    'diffEditor.removedLineBackground': '#c1444d14',
    'diffEditor.diagonalFill': '#e6e9ee',
  },
}

export const THEME_DATA: Record<ThemeName, monacoNs.editor.IStandaloneThemeData> = { dark, light }
